# Generated by Django 3.2.9 on 2022-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dateofuse',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='timeuse',
            field=models.CharField(max_length=50),
        ),
    ]
