# Generated by Django 3.2.9 on 2022-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0003_roomreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=50, unique=True)),
                ('roomtype', models.CharField(max_length=50)),
            ],
        ),
    ]
