# Generated by Django 3.2.9 on 2022-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='barangay',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
