# Generated by Django 3.2.9 on 2022-03-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0006_auto_20220307_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username+', to='conferenceroom.user', to_field='username'),
        ),
    ]
