# Generated by Django 3.2.9 on 2022-03-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0007_alter_room_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.AlterField(
            model_name='room',
            name='emailadd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailadd+', to='conferenceroom.user', to_field='emailadd'),
        ),
    ]
