# Generated by Django 3.2.9 on 2022-03-12 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceroom', '0010_auto_20220312_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomnumber',
        ),
        migrations.RemoveField(
            model_name='room',
            name='timeuse',
        ),
        migrations.AddField(
            model_name='room',
            name='slot',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='contactNum',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailadd',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
